### ISSUE TITLE
No Data from IMU Topics with MTi-1-8A7G6 Using

### ISSUE THREAD

**Issue by miksiWan** [xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client#11]
Hi, 

I'm receiving data from the `/imu/acceleration` and `/imu/angular_velocity` topics, but the` /imu/data` topic has not been created.

### Platform:
Ubuntu 22.04 Humble
Device: MTi-1-8A7G6

`$ros2 launch xsens_mti_ros2_driver xsens_mti_node.launch.py
`

> [INFO] [launch]: All log files can be found below /home/car50bee/.ros/log/2024-11-08-14-38-45-752147-car50bee-pc-47231
> [INFO] [launch]: Default logging verbosity is set to INFO
> [INFO] [xsens_mti_node-1]: process started with pid [47232]
> [xsens_mti_node-1] [INFO] [1731065925.809837872] [xsens_mti_node]: Rosnode time_option parameter is utc time from MTi
> [xsens_mti_node-1] [INFO] [1731065925.809953344] [xsens_mti_node]: Creating XsControl object...
> [xsens_mti_node-1] [INFO] [1731065925.810981555] [xsens_mti_node]: XdaInterface has been initialized
> [xsens_mti_node-1] [INFO] [1731065925.811115685] [xsens_mti_node]: Baudrate parameter: 115200
> [xsens_mti_node-1] [INFO] [1731065925.811136459] [xsens_mti_node]: Port name parameter: /dev/xsens_imu
> [xsens_mti_node-1] [INFO] [1731065925.811160399] [xsens_mti_node]: Scanning port /dev/xsens_imu ...
> [xsens_mti_node-1] [INFO] [1731065925.837183251] [xsens_mti_node]: Found a device with ID: 01884FAD @ port: /dev/xsens_imu, baudrate: 115200
> [xsens_mti_node-1] [INFO] [1731065925.837225521] [xsens_mti_node]: Opening port /dev/xsens_imu ...
> [xsens_mti_node-1] [INFO] [1731065925.878727138] [xsens_mti_node]: Device: MTi-1-8A7G6, with ID: 01884FAD opened.
> [xsens_mti_node-1] [INFO] [1731065925.878783391] [xsens_mti_node]: Firmware version: 1.20.0 build 5866 rev 123997
> [xsens_mti_node-1] [INFO] [1731065925.882955646] [xsens_mti_node]: Onboard Kalman Filter Option: 0.0 
> [xsens_mti_node-1] [INFO] [1731065925.895980201] [xsens_mti_node]: enable_deviceConfig is false, no need to configure MTI.
> [xsens_mti_node-1] [INFO] [1731065925.896036267] [xsens_mti_node]: Rosnode time_option is utc time from MTi
> [xsens_mti_node-1] [INFO] [1731065926.029182357] [xsens_mti_node]: Measuring ..
> [xsens_mti_node-1] [INFO] [1731065926.099443281] [xsens_mti_node]: Manual Gyro Bias Estimation is disabled.
> 

`$ros2 topic list
`
> /imu/acceleration
> /imu/acceleration_hr
> /imu/angular_velocity
> /imu/angular_velocity_hr
> /imu/dq
> /imu/dv
> /imu/mag
> /imu/time_ref
> /imu/utctime
> 

Parameter file:

>     ros__parameters:
> 
>         scan_for_devices: false
> 
>         port: '/dev/xsens_imu' # Uncomment and set your device's port.
>         baudrate: 115200 #921600     # Uncomment and set your device's baudrate.
> 
>         publisher_queue_size: 5
> 
>         time_option: 0
> 
>         enable_logging: false
> 
>         enable_deviceConfig: false
> 
>         enable_filter_config: false
> 
>         mti_filter_option: 0
> 
>         mti620630filterlabel_rollpitch: "Robust"
> 
>         mti620630filterlabel_yaw: "NorthReference"
> 
>         enable_active_heading_stabilization: false
> 
>         GNSS_LeverArm: [0.0, 0.0, 0.0] 
> 
>         ublox_platform: 0 
> 
>         enable_beidou: false
> 
> 
>         pub_utctime: true
>         pub_sampletime: true
>         pub_imu: true
>         pub_quaternion: true
>         pub_euler: true
>         pub_free_acceleration: true
>         pub_angular_velocity: true
>         pub_acceleration: true
>         pub_dq: true
>         pub_dv: true
>         pub_mag: true
>         pub_temperature: true
>         pub_pressure: true
>         pub_accelerationhr: true #High Rate Data Acceleration, when this is true, set enable_high_rate to true as well
>         pub_angular_velocity_hr: true #High Rate Data Angular Velocity,  when this is true, set enable_high_rate to true as well
>         pub_transform: true
>         pub_status: true
>         pub_twist: false         # For GNSS/INS Version of MTI only
>         pub_gnss: false          # For GNSS/INS Version of MTI only
>         pub_positionLLA: false   # For GNSS/INS Version of MTI only
>         pub_velocity: false      # For GNSS/INS Version of MTI only
>         pub_nmea: false          # For GNSS/INS Version of MTI only
>         pub_gnsspose: false      # For GNSS/INS Version of MTI only
> 
> 
>         output_data_rate: 100
> 
>         output_data_rate_lower: 100
>         output_data_rate_baro_mtione: 50
> 
> 
>         enable_high_rate: true
>         output_data_rate_acchr: 200 #1000
>         output_date_rate_gyrohr: 200 #1000
> 
> 
>         enable_orientation_smoother: false #valid for MTi-G-710, MTi-670(G), MTi-680(G)
>         enable_position_velocity_smoother: false #valid for MTi-680(G) only
>         enable_continuous_zero_rotation_update: false #valid for MTi-680(G) only
> 
>         enable_inrun_compass_calibration: false
> 
> 
>         enable_setting_baudrate: true
>         set_baudrate_value: 115200 #921600
> 
> 
>         enable_manual_gyro_bias: false
> 
>         manual_gyro_bias_param: [15, 5] # [event_interval, duration]
> 
> 
>         linear_acceleration_stddev: [0.0, 0.0, 0.0] # [m/s^2] Standard deviation for linear acceleration
>         angular_velocity_stddev: [0.0, 0.0, 0.0]   # [rad/s] Standard deviation for angular velocity
>         orientation_stddev: [0.0, 0.0, 0.0]        # [rad]   Standard deviation for orientation
>         magnetic_field_stddev: [0.0, 0.0, 0.0]     # [Tesla] Standard deviation for magnetic field
>

**Comment by xsenssupport** [comment]
If you want to configure the MTi using the yaml file, please make sure you had changed the parameter enable_deviceConfig: true. Then do 'colcon build'
