### ISSUE TITLE
MTi320 detection on ros2 HUMBLE

### ISSUE THREAD

**Issue by Ktysai** [xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client#2]
Hi there!

Thank you for the previous info. I have now ROS2 Humble.

My IMU is MTi320.

In your README this line had to be transformed in order to install this package

`pushd src/xsens_mti_ros2_driver/lib/xspublic && make && popd`

like this:
`pushd src/Xsens_MTi_ROS_Driver_and_Ntrip_Client/src/xsens_mti_ros2_driver/lib/xspublic && make && popd`

The  'colcon build' was fine, but on the first run I've got the following message:

`ubuuser@vioJetson:~/ros2_ws$ ros2 launch xsens_mti_ros2_driver xsens_mti_node.launch.py
[INFO] [launch]: All log files can be found below /home/ubuuser/.ros/log/2024-07-05-17-37-42-201489-vioJetson-13536
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [xsens_mti_node-1]: process started with pid [13537]
[xsens_mti_node-1] [INFO] [1720190262.337036180] [xsens_mti_node]: Creating XsControl object...
[xsens_mti_node-1] [INFO] [1720190262.348584494] [xsens_mti_node]: Scanning for devices...
[xsens_mti_node-1] [ERROR] [1720190262.379641694] [xsens_mti_node]: No MTi device found.
[xsens_mti_node-1] [INFO] [1720190262.379773188] [xsens_mti_node]: Cleaning up ...
[ERROR] [xsens_mti_node-1]: process has died [pid 13537, exit code 255, cmd '/home/ubuuser/ros2_ws/install/xsens_mti_ros2_driver/lib/xsens_mti_ros2_driver/xsens_mti_node --ros-args -r __node:=xsens_mti_node --params-file /home/ubuuser/ros2_ws/install/xsens_mti_ros2_driver/share/xsens_mti_ros2_driver/param/xsens_mti_node.yaml'].`

All the best!

**Comment by xsenssupport** [comment]
- The device is recognized, but I cannot ever access the device -

        Make sure you are in the correct group (often dialout or uucp) in order to
        access the device. You can test this with

            $ ls -l /dev/ttyUSB0
            crw-rw---- 1 root dialout 188, 0 May  6 16:21 /dev/ttyUSB0
            $ groups
            dialout audio video usb users plugdev

        If you aren't in the correct group, you can fix this in two ways.

        1. Add yourself to the correct group
            You can add yourself to it by using your distributions user management
            tool, or call

                $ sudo usermod -G dialout -a $USER

            Be sure to replace dialout with the actual group name if it is
            different. After adding yourself to the group, reboot then relogin.

**Comment by Ktysai** [comment]
Thank you!

The axis are messed up, but it works. 

My plan us to add MTI-320 URDF and STL file and change the launch file to point at this URF file.

I have to reflash my jetson Orin NX before this test.
