### ISSUE TITLE
No MTi device found.

### ISSUE THREAD

**Issue by ManChrys** [xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client#6]
i have a xsens mti 670 dk and connect it to my khadas vim 4 using rs232-to-usb cable. 

`khadas@Khadas:~/ws_livox$ ros2 launch xsens_mti_ros2_driver xsens_mti_node.launch.py
[INFO] [launch]: All log files can be found below /home/khadas/.ros/log/2024-10-06-23-45-43-263875-Khadas-4379
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [xsens_mti_node-1]: process started with pid [4380]
[xsens_mti_node-1] [INFO] [1728258343.459303453] [xsens_mti_node]: Rosnode time_option parameter is utc time from MTi
[xsens_mti_node-1] [INFO] [1728258343.459563408] [xsens_mti_node]: Creating XsControl object...
[xsens_mti_node-1] [INFO] [1728258343.461584511] [xsens_mti_node]: XdaInterface has been initialized
[xsens_mti_node-1] [INFO] [1728258343.461680134] [xsens_mti_node]: Scanning for devices...
[xsens_mti_node-1] [ERROR] [1728258343.499345796] [xsens_mti_node]: No MTi device found.
[xsens_mti_node-1] [ERROR] [1728258343.499503253] [xsens_mti_node]: Failed to connect device
[xsens_mti_node-1] [INFO] [1728258343.499544919] [xsens_mti_node]: Cleaning up ...
[ERROR] [xsens_mti_node-1]: process has died [pid 4380, exit code 255, cmd '/home/khadas/ws_livox/install/xsens_mti_ros2_driver/lib/xsens_mti_ros2_driver/xsens_mti_node --ros-args -r __node:=xsens_mti_node --params-file /home/khadas/ws_livox/install/xsens_mti_ros2_driver/share/xsens_mti_ros2_driver/param/xsens_mti_node.yaml'].
`

i dont know if it has to do with the ch34 driver

```
khadas@Khadas:~/ws_livox$ dmesg | grep ttyUSB
[  255.994126] usb 1-1.2: ch34x converter now attached to ttyUSB0
```

but when i try this i can see that i have some messages but the error still exists

khadas@Khadas:~/ws_livox$ sudo minicom -D /dev/ttyUSB0 -b 921600

![image](https://github.com/user-attachments/assets/89c1ca80-132e-4e3c-bec8-6fa46b8a5026)

i tried through yaml to set the port and baudrate but still the same error.

i would be really appreciated if you have any solution.

Thanks in advance.

**Comment by ManChrys** [comment]
**_update_**

```
Serial Devices:

ls /dev/ttyS*
/dev/ttyS0  /dev/ttyS1

ls /dev/ttyUSB*
/dev/ttyUSB0

ls /dev/ttyACM*
ls: cannot access '/dev/ttyACM*': No such file or directory

USB Devices:

lsusb
Bus 001 Device 007: ID 1a86:7523 QinHeng Electronics CH340 serial converter

Kernel Messages:

    [5569.477678] usb 1-1.1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.54
    [5569.480109] ch341 1-1.1:1.0: ch341-uart converter detected
    [5569.482026] usb 1-1.1: ch341-uart converter now attached to ttyUSB0
```

Conclusion:

    The system recognizes RS232-to-USB adapter as a CH341 serial converter, connected to /dev/ttyUSB0.
    The device is correctly detected by the system.
    
    Then i tried too
    
    sudo nano /etc/udev/rules.d/99-xsens.rules
    
    and add this
    
    SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", MODE="0666", SYMLINK+="xsens"
    
    sudo udevadm control --reload-rules
    
    sudo udevadm trigger
    
    khadas@Khadas:~/ws-livox$ ls -l /dev/xsens
lrwxrwxrwx 1 root root 7 Oct  7 20:09 /dev/xsens -> ttyUSB0


but still same error.

**Comment by xsenssupport** [comment]
Hi, 
Can you try with `cutecom` to see if you could receive the correct data:
```
sudo apt install cutecom
```
then run the program:
```
cutecom
```
After that, you could open the /dev/ttyUSB0 with the specified baudrate, in your case, change the baudrate to 921600.
Then in the receive data section, change the format to HEX, and see if you could receive FA FF 36 bytes.

**Comment by ManChrys** [comment]
Hello @xsenssupport ,

i tried your suggest and seems that i receive the data correctly, after i reinstall xsens mti driver.
