### ISSUE TITLE
Khadas as External device triggers

### ISSUE THREAD

**Issue by ManChrys** [xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client#7]
Hello @xsenssupport ,

I want to use khadas vim 4 (as it supports hardware time sync )  to time sync my xsens mti 670 dk.

Ubuntu 22.04.5 LTS
ROS2

I connect khadas vim 4 pin16 to xsens mti 670 dk pin9 and khadas vim4 pin9 to xsens pin2

khadas vim4 gpio header
GPIO num	Name	Pin
	                 GND	9

GPIO num	Name	Pin
 490	                 PIN.Y6	16

How can i check if xsens receive the time pulse, correctly? Mt Manager cant be installed in khadas vim4 so is there any other way to check it ?

Also in time synchronization options in Mti Manager except clock bias (line1 as i use pin9)  should i add another option to achieve my goal?

Also i should check /imu/time_ref topic or /imu/utctime to see if xsens receive the master clock time correct or its the same as they have the same header/stamp ?

> imu/time_ref	sensor_msgs/TimeReference	SampleTimeFine timestamp from device	depending on packet
> 
> imu/utctime	sensor_msgs/TimeReference	UTC Time from the device	depending on packet
> 

Thanks in advance.

**Comment by xsenssupport** [comment]
for technical questions, please send to support@movella.com
