### ISSUE TITLE
works on Ubuntu 22.04 with ros2 Foxy?

### ISSUE THREAD

**Issue by XabierSener** [xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client#8]
Hi i have a xsens mti DK 680 device. I see that you have a ros2 version. 

Mi doubt is if it works con ros2 foxy. I download the repo under a workspace in my nvidia jetson xavier I tried to build it bat always have compilation failure. 

In what ros distro is tested? Is there any ros 2 foxy version?

Another question, I have the Xsens driver running, downloaded from another repository. I also have the ntrip_client configured to launch individually, obtained from a different repository. My question is whether, by launching the .launch file for the Xsens driver individually and then the .launch file for the ntrip_client, the connection between them is automatically established to get the corrected positioning.

Thanks a lot 

Xabier

**Comment by xsenssupport** [comment]
for foxy, please see this closed [issue](https://github.com/xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client/issues/1).
The `xsens_ros_mti_driver` publishes the `/nmea` ros topic, and subscribes to `/rtcm` topic, and the `ntrip` subscribes the `/nmea` ros topic and once it gets the RTCM messages, it will pubsh at `/rtcm`, so they are automatically linked to each other. But you need to make sure the antenna is out door, and the output configuration is configured as stated in the readme.
